login_page:
    path: /login
    defaults: { _controller: UserBundle:Security:login }

login_check:
    path: /login-check
    defaults: { _controller: UserBundle:Security:loginCheck }

logout:
    path: /logout
    defaults: { _controller: UserBundle:Security:logout }