security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login_page
            logout:
                path:   logout
                target: photo_home
            anonymous: ~

    access_control:
        - { path: ^/dashboard, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/upload/, roles: ROLE_ADMIN }
        - { path: ^/delete/, roles: ROLE_ADMIN }
        - { path: ^/delete-photo/, roles: ROLE_ADMIN }
